### ISSUE TITLE
Extension throws error when clicking any button

### ISSUE THREAD

**Issue by justbispo** [hverlin/mise-vscode#51]
After https://github.com/hverlin/mise-vscode/issues/45 was solved, I've noticed that nothing actually works. It doesn't detect my tasks, tools or env vars. When I click on any button in the, it throws this error as a notification, with the command name changing depending on which button I clicked:
```
Error running command mise.someCommand: command 'mise.someCommand' not found. This is likely caused by the extension that contributes mise.someCommand.
```
The same `command mise.someCommand not found` error is shown if I try to run the commands from the command palette.
Unlike https://github.com/hverlin/mise-vscode/issues/45, the output tab doesn't show any error.
I think this issue was also happening yesterday but I thought something was wrong with my `mise.toml` that made it not show any tasks or tools.

**Comment by hverlin** [comment]
I will look into windows next week. I did some very basic testing in a Windows 10 VM for the previous ticket. You can see that here: https://github.com/hverlin/mise-vscode/issues/45#issuecomment-2528359490 tasks, environment variables and tasks were detected.

You are welcome to submit a PR if you find something. Here is how to start it locally: https://github.com/hverlin/mise-vscode/blob/main/CONTRIBUTING.md#running-the-extension-locally

**Comment by justbispo** [comment]
I've followed your advice, run `mise run dev` and it seems to be working correctly. Maybe the build in the marketplace isn't working correctly?
Although I also tried `mise run test` and it shows errors related with dirs, but doesn't seem to impact the usage of the extension.
<details>
  <summary>Tests</summary>

```diff
bun test v1.1.38 (bf2f153f)

src\package-json.test.ts:
✓ package.json configuration tests > ignore list should be correct [16.00ms]

src\utils\miseDoctorParser.test.ts:
24 |                            shims: "/dev/home/.local/share/mise/shims",
25 |                    },
26 |            };
27 |
28 |            const result = parseMiseConfig(input);
29 |            expect(result.dirs).toEqual(expected.dirs);
                           ^
error: expect(received).toEqual(expected)

  {
+   cache: "\\dev\\home\\Library\\Caches\\mise",
+   config: "\\dev\\home\\.config\\mise",
+   data: "\\dev\\home\\.local\\share\\mise",
+   shims: "\\dev\\home\\.local\\share\\mise\\shims",
+   state: "\\dev\\home\\.local\\state\\mise",
-   cache: "/dev/home/Library/Caches/mise",
-   config: "/dev/home/.config/mise",
-   data: "/dev/home/.local/share/mise",
-   shims: "/dev/home/.local/share/mise/shims",
-   state: "/dev/home/.local/state/mise",
  }

- Expected  - 5
+ Received  + 5

      at C:\Users\Bispo\mise-vscode\src\utils\miseDoctorParser.test.ts:29:23
✗ mise doctor parser > should parse dirs section correctly
✓ mise doctor parser > should handle empty dirs section
✓ mise doctor parser > should handle missing dirs section
70 |                            shims: "/dev/home/.local/share/mise/shims",
71 |                    },
72 |            };
73 |
74 |            const result = parseMiseConfig(input);
75 |            expect(result.dirs).toEqual(expected.dirs);
                           ^
error: expect(received).toEqual(expected)

  {
+   cache: "\\dev\\home\\Library\\Caches\\mise",
+   config: "\\dev\\home\\.config\\mise",
+   data: "\\dev\\home\\.local\\share\\mise",
+   shims: "\\dev\\home\\.local\\share\\mise\\shims",
+   state: "\\dev\\home\\.local\\state\\mise",
-   cache: "/dev/home/Library/Caches/mise",
-   config: "/dev/home/.config/mise",
-   data: "/dev/home/.local/share/mise",
-   shims: "/dev/home/.local/share/mise/shims",
-   state: "/dev/home/.local/state/mise",
  }

- Expected  - 5
+ Received  + 5

      at C:\Users\Bispo\mise-vscode\src\utils\miseDoctorParser.test.ts:75:23
✗ mise doctor parser > should handle different indentation levels
90 |                            shims: "",
91 |                    },
92 |            };
93 |
94 |            const result = parseMiseConfig(input);
95 |            expect(result.dirs).toEqual(expected.dirs);
                           ^
error: expect(received).toEqual(expected)

  {
+   config: "\\dev\\home\\.config\\mise",
+   data: "\\dev\\home\\.local\\share\\mise",
-   config: "/dev/home/.config/mise",
-   data: "/dev/home/.local/share/mise",
    shims: "",
  }

- Expected  - 2
+ Received  + 2

      at C:\Users\Bispo\mise-vscode\src\utils\miseDoctorParser.test.ts:95:23
✗ mise doctor parser > should handle malformed lines in dirs section
124 |                           shims: "/dev/home/.local/share/mise/shims",
125 |                   },
126 |           };
127 |
128 |           const result = parseMiseConfig(input);
129 |           expect(result.dirs).toEqual(expected.dirs);
                            ^
error: expect(received).toEqual(expected)

  {
+   cache: "\\dev\\home\\Library\\Caches\\mise",
+   config: "\\dev\\home\\.config\\mise",
+   data: "\\dev\\home\\.local\\share\\mise",
+   shims: "\\dev\\home\\.local\\share\\mise\\shims",
+   state: "\\dev\\home\\.local\\state\\mise",
-   cache: "/dev/home/Library/Caches/mise",
-   config: "/dev/home/.config/mise",
-   data: "/dev/home/.local/share/mise",
-   shims: "/dev/home/.local/share/mise/shims",
-   state: "/dev/home/.local/state/mise",
  }

- Expected  - 5
+ Received  + 5

      at C:\Users\Bispo\mise-vscode\src\utils\miseDoctorParser.test.ts:129:23
✗ mise doctor parser > should handle real-world mise output
✓ mise doctor parser > should parse mise version correctly

src\utils\taskInfoParser.test.ts:
✓ parseUsageSpecLine > parses name correctly
✓ parseUsageSpecLine > parses bin correctly
✓ parseUsageSpecLine > parses simple flag correctly
✓ parseUsageSpecLine > parses flag with argument correctly
✓ parseUsageSpecLine > parses required argument correctly
✓ parseUsageSpecLine > handles malformed input gracefully
✓ parseTaskInfo > parses complete task info correctly
✓ parseTaskInfo > handles minimal task info correctly
✓ parseTaskInfo > handles empty lines and extra whitespace
✓ parseTaskInfo > handles missing optional fields
✓ parseTaskInfo > handles multiple flags and args
✓ parseTaskInfo > handles multiline run commands
✓ parseTaskInfo > example cargo task

 17 pass
 4 fail
 29 expect() calls
Ran 21 tests across 3 files. [255.00ms]
[test] ERROR task failed
```

</details>

**Comment by justbispo** [comment]
I've tested on my main desktop, Arch Linux, and the same issue is happening.

**Comment by hverlin** [comment]
I have installed on other computers than mine successfully, so I think it's packaged correctly.

The only case where you would see this error is if it fails in the main `activate` function, before any of the `registerCommand`. However, there are no early `return`. If it throws, VSCode should show an error notification. 

If you get a chance to retry it, the next version will have error logs if initialization fails

**Comment by justbispo** [comment]
After a bit of testing, I can only make the extension work correctly if the project directory is exactly named "mise-vscode". Maybe the extension is using an hardcoded name somewhere?
Also, with the last updates, it doesn't show any errors, it even shows the PATH env var and I can add tasks to mise.toml, but it can't detect them.

**Comment by hverlin** [comment]
If you don't see any tasks, try running `mise trust`. I think the recent change in behavior might have caused the files to be automatically ignored when created manually

**Comment by hverlin** [comment]
Created https://github.com/jdx/mise/issues/3560
I will also add an option (true by default) which will run `mise trust` if the VSCode workspace is trusted (I will disable the extension in non-trusted workspaces also)

**Comment by hverlin** [comment]
Added the new option https://hverlin.github.io/mise-vscode/reference/settings/#miseautomaticallytrustmiseconfigfiles (enabled by default). Please let me know if you are still seeing issues

**Comment by justbispo** [comment]
I don't know if it the last version of the extension or running `mise trust`, but it's fixed. I do know that I had previously run `mise trust` on the project I'm testing and it didn't seem the reason for the extension not working.
