### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by ssbarnea** [hverlin/mise-vscode#62]
I am opening multiple projects in a single workspace all the time (99%), so the lack of support for them is a deal-breaker. Let's use this issue for tracking adding support for it.

**Comment by hverlin** [comment]
I agree. I have added a note in the README already.  Currently, it only uses the primary workspace.

I am not sure yet how the extension should behave in multi-folders mode. Do you have a good example of such extension? 

— For tools/tasks/env tree views, I think we can easily fetch them in each workspace
— There is a `direnv` like feature where vscode loads the environment variables provided by `mise`. I am not sure how this can work in multi-root workspaces. I will probably have to let the user choose what they need, or switch the environment variables based on the file they are looking at.
— I need to understand a bit better how settings work in multi-root mode. I am writing to the settings.json file of the workspace now, and I am not sure yet if this approach will work in multi-root mode

**Comment by hverlin** [comment]
Added the ability to select which folder to use in multi-root workspaces, see docs:
https://hverlin.github.io/mise-vscode/reference/mutli-folders/

I might add a warning/info if opening a `mise.toml` file in a folder that is not currently selected to make it easier to switch
